# Generated by Django 2.1.7 on 2019-03-29 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_votes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='user',
        ),
        migrations.AlterField(
            model_name='votes',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Article'),
        ),
    ]
