# Generated by Django 2.1.7 on 2019-03-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190329_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
